const seed=[
{name:'HVAC filter',category:'Air',intervalDays:90,lastServiceDate:'2026-07-01',notes:'20x20x1 filter'},
{name:'Dryer vent',category:'Laundry',intervalDays:180,lastServiceDate:'2026-03-10',notes:'Clean exterior flap too'},
{name:'Smoke detector test',category:'Safety',intervalDays:90,lastServiceDate:'2026-06-15',notes:'Test all units'},
{name:'Water heater flush',category:'Plumbing',intervalDays:365,lastServiceDate:'2025-10-01',notes:'Annual sediment flush'}
];
const KEY='homeops-webmcp-v1';
const today=()=>new Date('2026-09-01T12:00:00');
const iso=d=>new Date(d).toISOString().slice(0,10);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
let items=load();
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function daysBetween(a,b){return Math.ceil((new Date(b)-new Date(a))/86400000)}
function enrich(i){const due=new Date(i.lastServiceDate);due.setDate(due.getDate()+Number(i.intervalDays));return {...i,dueDate:iso(due),daysRemaining:daysBetween(today(),due)}}
function due(horizon=30){return items.map(enrich).filter(x=>x.daysRemaining<=horizon).sort((a,b)=>a.daysRemaining-b.daysRemaining)}
function lookup(name){const q=name.toLowerCase();const i=items.find(x=>x.name.toLowerCase().includes(q)||q.includes(x.name.toLowerCase()));return i?enrich(i):null}
function logService({name,date,note=''}){let i=lookup(name);if(!i)throw new Error(`No item found for ${name}`);const raw=items.find(x=>x.name===i.name);raw.lastServiceDate=date||iso(today());if(note)raw.notes=note;save();return enrich(raw)}
function addItem({name,intervalDays,category='Home',lastServiceDate,notes=''}){if(!name||!intervalDays)throw new Error('name and intervalDays are required');const existing=lookup(name);if(existing)throw new Error('A similar item already exists');const obj={name,intervalDays:Number(intervalDays),category,lastServiceDate:lastServiceDate||iso(today()),notes};items.push(obj);save();return enrich(obj)}
function planNext({horizonDays=30,limit=3}={}){return due(horizonDays).slice(0,limit).map((x,idx)=>({priority:idx+1,name:x.name,dueDate:x.dueDate,daysRemaining:x.daysRemaining,reason:x.daysRemaining<0?`${Math.abs(x.daysRemaining)} days overdue`:`due in ${x.daysRemaining} days`}))}
function render(){const all=items.map(enrich);const urgent=all.filter(x=>x.daysRemaining<0).length;const soon=all.filter(x=>x.daysRemaining>=0&&x.daysRemaining<=30).length;document.getElementById('stats').innerHTML=`<div class="stat"><b>${items.length}</b><span>tracked responsibilities</span></div><div class="stat"><b>${urgent}</b><span>overdue now</span></div><div class="stat"><b>${soon}</b><span>due in 30 days</span></div>`;const list=due(30);document.getElementById('dueList').innerHTML=list.length?list.map(x=>`<div class="due"><div class="row"><strong>${x.name}</strong><span class="badge ${x.daysRemaining<0?'overdue':x.daysRemaining<=10?'soon':''}">${x.daysRemaining<0?Math.abs(x.daysRemaining)+'d overdue':x.daysRemaining===0?'due today':x.daysRemaining+'d'}</span></div><div class="meta">Next due ${x.dueDate} · ${x.category}</div></div>`).join(''):'<div class="due">Nothing is due in the next 30 days.</div>';document.getElementById('itemsGrid').innerHTML=all.map(x=>`<div class="item"><div class="row"><strong>${x.name}</strong><span class="badge">${x.category}</span></div><div class="meta">Last serviced ${x.lastServiceDate} · every ${x.intervalDays} days</div>${x.notes?`<div class="meta">${x.notes}</div>`:''}</div>`).join('')}
function pretty(v){return JSON.stringify(v,null,2)}
async function runDemo(){const log=document.getElementById('agentLog');const p=planNext({horizonDays:30,limit:3});log.textContent='Agent called homeops_plan_next\n\n'+pretty(p)+'\n\nThe visible brief and agent-readable state refer to the same household memory.'}
document.getElementById('agentDemo').onclick=runDemo;document.getElementById('reset').onclick=()=>{items=structuredClone(seed);save();document.getElementById('agentLog').textContent='Demo reset. Ready for an agent task.'};
async function registerWebMCP(){const mc=document.modelContext||navigator.modelContext;const indicator=document.getElementById('webmcpStatus');if(!mc?.registerTool){indicator.textContent='WEBMCP READY · ENABLE SUPPORTED BROWSER';return}const options={};const tools=[
{name:'homeops_list_due',description:'List household maintenance that is overdue or due within a time horizon.',inputSchema:{type:'object',properties:{horizonDays:{type:'number',minimum:0,default:30}}},annotations:{readOnlyHint:true},execute:async({horizonDays=30}={})=>({items:due(horizonDays)})},
{name:'homeops_lookup_item',description:'Look up a household maintenance item, its last service date, saved notes, and next due date.',inputSchema:{type:'object',properties:{name:{type:'string'}},required:['name']},annotations:{readOnlyHint:true},execute:async({name})=>{const item=lookup(name);if(!item)throw new Error('Item not found');return {item}}},
{name:'homeops_log_service',description:'Record completed household maintenance. This mutates durable browser state and updates the visible HomeOps UI.',inputSchema:{type:'object',properties:{name:{type:'string'},date:{type:'string'},note:{type:'string'}},required:['name']},annotations:{readOnlyHint:false},execute:async(args)=>({item:logService(args),message:'Service recorded'})},
{name:'homeops_add_item',description:'Add a new recurring household maintenance responsibility to HomeOps.',inputSchema:{type:'object',properties:{name:{type:'string'},intervalDays:{type:'number',minimum:1},category:{type:'string'},lastServiceDate:{type:'string'},notes:{type:'string'}},required:['name','intervalDays']},annotations:{readOnlyHint:false},execute:async(args)=>({item:addItem(args),message:'Maintenance item added'})},
{name:'homeops_plan_next',description:'Create a prioritized maintenance action plan for the requested time horizon using HomeOps household memory.',inputSchema:{type:'object',properties:{horizonDays:{type:'number',minimum:0,default:30},limit:{type:'number',minimum:1,maximum:10,default:3}}},annotations:{readOnlyHint:true},execute:async(args={})=>({plan:planNext(args)})}
];try{for(const t of tools)await mc.registerTool(t,options);indicator.textContent=`WEBMCP LIVE · ${tools.length} TOOLS`;indicator.style.color='#83f1bc'}catch(e){console.error(e);indicator.textContent='WEBMCP REGISTRATION ERROR'}}
render();registerWebMCP();